import { Injectable } from '@nestjs/common';
import { AiService } from '../ai/ai.service';
import { FieldDefinition } from '../blueprint/interfaces/blueprint.interface';

@Injectable()
export class GenerationService {
  constructor(private readonly aiService: AiService) {}

  /**
   * Generate a question to ask the user for a specific field for the first time.
   * @param field The field definition containing the question template and context
   * @returns A natural language question generated by the AI
   */
  async generateQuestion(field: FieldDefinition): Promise<string> {
    const systemPrompt =
      'You are a helpful assistant collecting data for a form. Your goal is to ask the user for the specific information required. Be polite and concise.';

    const userMessage = `Ask the user for the following field: '${field.questionTemplate}'. Context/Reason: '${field.aiContext}'.`;

    return await this.aiService.chat(systemPrompt, userMessage);
  }

  /**
   * Generate an error response when user input fails local validation.
   * Explains the error gently and re-asks the question.
   * @param field The field definition that failed validation
   * @param invalidInput The user's invalid input
   * @param errorReason The reason why the input was invalid
   * @returns A natural language error message and re-prompt
   */
  async generateErrorResponse(
    field: FieldDefinition,
    invalidInput: string,
    errorReason: string,
  ): Promise<string> {
    const systemPrompt =
      'You are a helpful assistant. The user tried to answer a question but provided invalid data. Explain the error gently and re-ask the question.';

    const userMessage = `We asked for '${field.questionTemplate}'. The user replied: '${invalidInput}'. This is invalid because: '${errorReason}'. Please ask them to correct it.`;

    return await this.aiService.chat(systemPrompt, userMessage);
  }

  /**
   * Generate a contextual response when the user asks a question instead of answering.
   * Answers their question using the blueprint context, then steers back to the form.
   * @param field The current field definition
   * @param userQuestion The user's question about the form
   * @returns A contextual answer followed by a re-prompt
   */
  async generateContextualResponse(
    field: FieldDefinition,
    userQuestion: string,
  ): Promise<string> {
    const systemPrompt =
      'You are a helpful assistant. The user has a question about the form. Answer their question based ONLY on the provided context, then politely re-ask the original question.';

    const userMessage = `The current field is '${field.questionTemplate}'. The Context is: '${field.aiContext}'. The user asked: '${userQuestion}'.`;

    return await this.aiService.chat(systemPrompt, userMessage);
  }
}
