import { Injectable } from '@nestjs/common';
import { AiService } from '../ai/ai.service';
import { PromptService } from '../config/prompt.service';
import { TemplateService } from '../template/template.service';
import { FieldDefinition } from '../blueprint/interfaces/blueprint.interface';

@Injectable()
export class GenerationService {
  constructor(
    private readonly aiService: AiService,
    private readonly promptService: PromptService,
    private readonly templateService: TemplateService,
  ) {}

  /**
   * Generate a question to ask the user for a specific field for the first time.
   * @param field The field definition containing the question template and context
   * @returns A natural language question generated by the AI
   */
  async generateQuestion(field: FieldDefinition): Promise<string> {
    const systemPromptTemplate = this.promptService.getPrompt('generation.question.system');
    const userPromptTemplate = this.promptService.getPrompt('generation.question.user');

    const userMessage = this.templateService.render(userPromptTemplate, {
      questionTemplate: field.questionTemplate,
      aiContext: field.aiContext,
    });

    return await this.aiService.chat(systemPromptTemplate, userMessage);
  }

  /**
   * Generate an error response when user input fails local validation.
   * Explains the error gently and re-asks the question.
   * @param field The field definition that failed validation
   * @param invalidInput The user's invalid input
   * @param errorReason The reason why the input was invalid
   * @returns A natural language error message and re-prompt
   */
  async generateErrorResponse(
    field: FieldDefinition,
    invalidInput: string,
    errorReason: string,
  ): Promise<string> {
    const systemPromptTemplate = this.promptService.getPrompt('generation.error.system');
    const userPromptTemplate = this.promptService.getPrompt('generation.error.user');

    const userMessage = this.templateService.render(userPromptTemplate, {
      questionTemplate: field.questionTemplate,
      invalidInput: invalidInput,
      errorReason: errorReason,
    });

    return await this.aiService.chat(systemPromptTemplate, userMessage);
  }

  /**
   * Generate a contextual response when the user asks a question instead of answering.
   * Answers their question using the blueprint context, then steers back to the form.
   * @param field The current field definition
   * @param userQuestion The user's question about the form
   * @returns A contextual answer followed by a re-prompt
   */
  async generateContextualResponse(
    field: FieldDefinition,
    userQuestion: string,
  ): Promise<string> {
    const systemPromptTemplate = this.promptService.getPrompt('generation.contextual.system');
    const userPromptTemplate = this.promptService.getPrompt('generation.contextual.user');

    const userMessage = this.templateService.render(userPromptTemplate, {
      questionTemplate: field.questionTemplate,
      aiContext: field.aiContext,
      userQuestion: userQuestion,
    });

    return await this.aiService.chat(systemPromptTemplate, userMessage);
  }
}
